language: rust
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
  - cargo fmt --all -- --check
  - |
    if [[ "$TRAVIS_RUST_VERSION" == nightly* ]]; then
      cargo build --no-default-features
    fi
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
install:
  - rustup component add rustfmt
