language: rust
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
  - cargo fmt --all -- --check
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
install:
  - rustup component add rustfmt
