[package]
name = "bls-aggregates"
version = "0.3.0"
authors = ["Lovesh Harchandani <lovesh.bond@gmail.com>"]
description = "Various signature schemes. BLS, MuSig"
license = "MIT/Apache-2.0"

[dependencies]
blake2-rfc = "0.2.18"
rand = "0.5.3"
lazy_static = "1.0"
amcl = { path = "./amcl" }
