[package]
name = "bls-aggregates"
version = "0.6.1"
authors = ["Lovesh Harchandani <lovesh.bond@gmail.com>"]
description = "Various signature schemes. BLS, MuSig"
license = "MIT/Apache-2.0"

[[bench]]
name = "bls381_benches"
harness = false

[dependencies]
amcl = { path = "./amcl", default-features = false }
hex = { version = "0.3", optional = true }
lazy_static = { version = "1.0", optional = true }
rand = { version = "0.5", default-features = false }
tiny-keccak = "1.4"
yaml-rust = { version = "0.4", optional = true }

# This cannot be specified as dev-dependencies. Otherwise a cargo bug will always resolve `rand` with `std` feature, which breaks `no_std` builds.
criterion = { version = "0.2", optional = true }

[features]
default = ["std"]
bench = ["criterion"]
std = [
  "amcl/std",
  "rand/std",
  "lazy_static",
  "hex",
  "yaml-rust",
]